PATH = "D:\\CAAGIS flow tracker\\"

MTP = PATH + "MTP\\"
PROJECT = PATH + "PROJECT\\"

SRCELIB = MTP + "SRCELIB\\"
COPYLIB = MTP + "COPYLIB\\"
INCLUDE = MTP + "INCLUDE\\"
EXPANDED = MTP + "EXPANDED\\"
PROCESSING = MTP + "PROCESSING\\"
TREES = MTP + "TREES\\"

DATA = PROJECT + "DATA\\"
