PATH = "D:\\CAAGIS flow tracker\\"

MTP = PATH + "MTP\\"
MTPZIP = PATH + "MTP ZIP\\"
PROJECT = PATH + "PROJECT\\"

SRCELIB = MTP + "SRCELIB\\"
COPYLIB = MTP + "COPYLIB\\"
INCLUDE = MTP + "INCLUDE\\"
EXPANDED = MTP + "EXPANDED\\"
PROCESSING = MTP + "PROCESSING\\"
TREES = MTP + "TREES\\"

SRCEZIP = MTPZIP + "SRCELIB.zip"
COPYZIP = MTPZIP + "COPYLIB.zip"
INCZIP = MTPZIP + "INCLUDE.zip"
EXPANDEDZIP = MTPZIP + "EXPANDED.zip"
PROCESSINGZIP = MTPZIP + "PROCESSING.zip"
TREESZIP = MTPZIP + "TREES.zip"

DATA = PROJECT + "DATA\\"

ZEROPAD = 8

FONT = ("Times New Roman",10,"bold")
NPLOCATION = "C:\\Program Files\\Notepad++\\notepad++.exe"

TOOLTIPSIZE = 30

BRANCHSPACE = 10
BLOCKSPACE = 10
LINEDIST = 30
ICONWIDTH = 80
ICONHEIGHT = ICONWIDTH/2
BLOCKHEIGHT = ICONHEIGHT + BLOCKSPACE + BLOCKSPACE
BRANCHWIDTH = ICONWIDTH + BRANCHSPACE + BRANCHSPACE

ICONS = PROJECT + "icons\\"

